env-var-prefix: "CLOUD"

service-name: "cloud_disk"

server-addr: ":8080"

appsalt: "some random string"

filesystem:
  driver: "os"
  root: "data"

database:
  driver: "mysql"
  host: "127.0.0.1"
  port: "3306"
  user: "root"
  password: "root"
  dbname: "cloud_disk"

redis:
  address: "127.0.0.1"
  port: "6379"

ticket:
  driver: "redis"
  ttl: 2592000

queue-num: 20

minio:
  host: "xxx"
  accesskey: "xxx"
  secretkey: "xxx"
  ssl: false
  bucketname: "xxx"

image-proxy:
  host: "xxx"
  omitbaseurl: true
